name: rando_new
description: "A new Flutter project for generating random tasks and fun facts using OpenAI API."
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.3.0  # For API requests to OpenAI
  shared_preferences: ^2.5.2  # For local storage of tasks & facts
  provider: ^6.1.2  # Optional state management (useful for future updates)
  google_fonts: ^6.2.1  # To enhance UI with custom fonts
  flutter_svg: ^2.0.10  # For high-quality vector icons
  cupertino_icons: ^1.0.8  # iOS-style icons
  firebase_core: ^3.12.1
  carousel_slider: ^4.0.0
  cloud_firestore: ^5.6.5
  firebase_messaging: ^15.2.4
  firebase_analytics: ^11.4.4
  firebase_auth: ^5.5.1
  animate_do: ^4.2.0
  lottie: ^3.3.1
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/profile_placeholder.png  
    - assets/animations/challenge_background.json
    - assets/animations/login_background.json
