name: rando_new
description: "A new Flutter project for generating random tasks and fun facts using OpenAI API."
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.3.0  # For API requests to OpenAI
  shared_preferences: ^2.5.2  # For local storage of tasks & facts
  provider: ^6.1.2  # Optional state management (useful for future updates)
  google_fonts: ^6.2.1  # To enhance UI with custom fonts
  flutter_svg: ^2.0.10  # For high-quality vector icons
  cupertino_icons: ^1.0.8  # iOS-style icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/profile_placeholder.jpeg  # Default profile image (add this image)
